export let arrayDeCitas = [
    { cita: "No hay que ir para atrás ni para darse impulso", autor: "Lao Tsé" },
    { cita: "No hay caminos para la paz; la paz es el camino", autor: "Mahatma Gandhi" },
    { cita: "Haz el amor y no la guerra", autor: "John Lennon" },
    { cita: "Para trabajar basta estar convencido de una cosa: que trabajar es menos aburrido que divertirse", autor: "Charles Baudelaire" },
    { cita: "Lo peor que hacen los malos es obligarnos a dudar de los buenos", autor: "Jacinto Benavente" },
    { cita: "Las guerras seguirán mientras el color de la piel siga siendo más importante que el de los ojos", autor: "Bob Marley" },
    { cita: "Aprende a vivir y sabrás morir bien", autor: "Confucio" },
    { cita: "Cada día sabemos más y entendemos menos", autor: "Albert Einstein" },
    { cita: "El mundo no está en peligro por las malas personas sino por aquellas que permiten la maldad", autor: "Albert Einstein" },
    { cita: "La medida del amor es amar sin medida", autor: "San Agustín" },
    { cita: "No hay nada que un hombre no sea capaz de hacer cuando una mujer le mira", autor: "Casanova" },
    { cita: "Dar el ejemplo no es la principal manera de influir sobre los demás; es la única manera.", autor: "Albert Einstein" },
    { cita: "El dinero no puede comprar la vida", autor: "Bob Marley" },
    { cita: "Si es bueno vivir, todavía es mejor soñar, y lo mejor de todo, despertar", autor: "Antonio Machado" },
    { cita: "La mayor declaración de amor es la que no se hace; el hombre que siente mucho, habla poco", autor: "Platón" },
    { cita: "Si das pescado a un hombre hambriento lo nutres durante una jornada. Si le enseñas a pescar, le nutrirás toda su vida", autor: "Lao Tsé" },
    { cita: "El poder no cambia a las personas, solo revela quiénes son realmente", autor: "Meryl Streep" },
    { cita: "Ningún hombre es lo bastante bueno para gobernar a otros sin su consentimiento.", autor: "Abraham Lincoln" },
    { cita: "Todo lo que se come sin necesidad se roba al estómago de los pobres", autor: "Mahatma Gandhi" },
    { cita: "Vivir sola es como estar en una fiesta donde nadie te hace caso", autor: "Marilyn Monroe" },
    { cita: "El cuerpo humano es el carruaje; el yo, el hombre que lo conduce; el pensamiento son las riendas, y los sentimientos, los caballos", autor: "Platón" },
    { cita: "Estar preparado es importante, saber esperarlo es aún más, pero aprovechar el momento adecuado es la clave de la vida", autor: "Arthur Schnitzler" },
    { cita: "No estoy tan enamorado de mis propias opiniones que ignore lo que los demás puedan pensar acerca de ellas", autor: "Copérnico" },
    { cita: "La más estricta justicia no creo que sea siempre la mejor política", autor: "Abraham Lincoln" },
    { cita: "El sabio no dice nunca todo lo que piensa, pero siempre piensa todo lo que dice", autor: "Aristóteles" },
    { cita: "Hay dos cosas que son infinitas: el universo y la estupidez humana; de la primera no estoy muy seguro", autor: "Albert Einstein" },
    { cita: "El nacimiento y la muerte no son dos estados distintos, sino dos aspectos del mismo estado", autor: "Mahatma Gandhi" },
    { cita: "Lo que importa verdaderamente en la vida no son los objetivos que nos marcamos, sino los caminos que seguimos para lograrlo", autor: "Peter Bamm" },
    { cita: "El mundo es bello, pero tiene un defecto llamado hombre", autor: "Friedrich Nietzsche" },
    { cita: "La pereza viaja tan despacio que la pobreza no tarda en alcanzarla", autor: "Benjamin Franklin" },
    { cita: "Una velada en que todos los presentes estén absolutamente de acuerdo es una velada perdida", autor: "Albert Einstein" },
    { cita: "Aprende como si fueras a vivir toda la vida y vive como si fueras a morir mañana", autor: "Charles Chaplin" },
    { cita: "El que no posee el don de maravillarse ni de entusiasmarse más le valdría estar muerto, porque sus ojos están cerrados", autor: "Albert Einstein" },
    { cita: "No te tomes la vida demasiado en serio; nunca saldrás de ella vivo", autor: "Elbert Hubbard" },
    { cita: "No hay más que dos maneras de vivir la vida: una como si nada fuera un milagro, la otra como si todo lo fuera", autor: "Albert Einstein" },
    { cita: "Haz el bien sin mirar a quién", autor: "Proverbio" },
    { cita: "La peor prisión es un corazón cerrado", autor: "John Ray" },
    { cita: "La educación es el arma más poderosa que puedes usar para cambiar el mundo", autor: "Nelson Mandela" },
    { cita: "Los hombres son como los vinos: la edad agria los malos y mejora los buenos", autor: "Cicerón" },
    { cita: "El único modo de hacer un gran trabajo es amar lo que haces", autor: "Steve Jobs" },
    { cita: "La mejor manera de predecir el futuro es creándolo", autor: "Peter Drucker" },
    { cita: "Lo que me preocupa no es que me hayas mentido, sino que, de ahora en adelante, ya no podré creerte", autor: "Friedrich Nietzsche" },
    { cita: "No hay más que un modo de ser feliz: vivir para los demás", autor: "León Tolstói" },
    { cita: "La paz comienza con una sonrisa", autor: "Madre Teresa de Calcuta" },
    { cita: "La medida del amor es amar sin medida", autor: "San Agustín" },
    { cita: "Las personas más bellas con las que me he encontrado son aquellas que han conocido la derrota, conocido el sufrimiento, conocido la lucha, conocido la pérdida y han encontrado su forma de salir de las profundidades", autor: "Elisabeth Kübler-Ross" },
    { cita: "La vida es lo que pasa mientras estás ocupado haciendo otros planes", autor: "John Lennon" },
    { cita: "Cuando haces lo que temes, el miedo muere de muerte natural", autor: "Berenice Bejo" },
    { cita: "No hay que ir para atrás ni para darse impulso", autor: "Lao Tsé" },
    { cita: "La mejor venganza es una vida bien vivida", autor: "Henry Rollins" },
    { cita: "Nuestro mayor miedo no es que seamos inadecuados. Nuestro miedo más profundo es que somos poderosos más allá de toda medida", autor: "Marianne Williamson" },
    { cita: "Lo que no te mata te hace más fuerte", autor: "Friedrich Nietzsche" },
    { cita: "Todo lo que somos es el resultado de lo que hemos pensado; está fundado en nuestros pensamientos y está hecho de nuestros pensamientos", autor: "Buda" },
    { cita: "La mayor gloria no es nunca caer, sino levantarse siempre", autor: "Confucio" },
    { cita: "El arte de vivir es saber cómo gastar no más de lo que se tiene", autor: "Marco Tulio Cicerón" },
    { cita: "Lo que se obtiene con violencia, solamente se puede mantener con violencia", autor: "Mahatma Gandhi" },
    { cita: "La única manera de hacer un gran trabajo es amar lo que haces", autor: "Steve Jobs" },
    { cita: "La simplicidad es la sofisticación máxima", autor: "Leonardo da Vinci" },
    { cita: "El pesimista se queja del viento; el optimista espera que cambie; el realista ajusta las velas", autor: "William George Ward" },
    { cita: "Sólo sé que no sé nada", autor: "Sócrates" },
    { cita: "La verdad es más importante que los hechos", autor: "Frank Lloyd Wright" },
    { cita: "No puedes depender de tus ojos cuando tu imaginación está fuera de foco", autor: "Mark Twain" },
    { cita: "El mayor enemigo del conocimiento no es la ignorancia, sino la ilusión del conocimiento", autor: "Stephen Hawking" },
    { cita: "La vida es lo que pasa mientras estás ocupado haciendo otros planes", autor: "John Lennon" },
    { cita: "La mayor gloria no es nunca caer, sino levantarse siempre", autor: "Confucio" },
    { cita: "La mejor manera de predecir el futuro es creándolo", autor: "Peter Drucker" },
    { cita: "La única manera de hacer un gran trabajo es amar lo que haces", autor: "Steve Jobs" },
    { cita: "La simplicidad es la sofisticación máxima", autor: "Leonardo da Vinci" },
    { cita: "El pesimista se queja del viento; el optimista espera que cambie; el realista ajusta las velas", autor: "William George Ward" },
    { cita: "Sólo sé que no sé nada", autor: "Sócrates" },
    { cita: "La verdad es más importante que los hechos", autor: "Frank Lloyd Wright" },
    { cita: "No puedes depender de tus ojos cuando tu imaginación está fuera de foco", autor: "Mark Twain" },
    { cita: "El mayor enemigo del conocimiento no es la ignorancia, sino la ilusión del conocimiento", autor: "Stephen Hawking" },
    { cita: "La vida es lo que pasa mientras estás ocupado haciendo otros planes", autor: "John Lennon" },
    { cita: "La mayor gloria no es nunca caer, sino levantarse siempre", autor: "Confucio" },
    { cita: "La mejor manera de predecir el futuro es creándolo", autor: "Peter Drucker" },
    { cita: "La única manera de hacer un gran trabajo es amar lo que haces", autor: "Steve Jobs" },
    { cita: "La simplicidad es la sofisticación máxima", autor: "Leonardo da Vinci" }];

